/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import Book.BookManager;
import Book.BookTypeManage;
import Book.BooksBorrow;
import Book.BooksReturn;
import Member.LoginDialog;
import Member.MemberManager;
import java.awt.event.WindowAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import manage.DbConnect;
import manage.Lang;
import manage.GlobalVar;
import manage.NetworkSetup;

/**
 *
 * @author khanchaiwongsit
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        //set Language
        Lang.myLang = "Thai";
        Lang.getLang();
        //set Form
        initComponents();
        setBounds(0, 0, GlobalVar.screenWidth, GlobalVar.screenHeight );
        setTitle(Lang.program_name);
       //
        desktop.setBounds(0, 50, GlobalVar.screenWidth, GlobalVar.screenHeight-50);
        //
    }
    
    
    public static Boolean getLogin() {
            Connection connect = null;
            PreparedStatement pre = null;
            Boolean status =false;
            try {
                    connect =  DbConnect.getConnection();	//connect Db
                    String sql = "SELECT *  FROM  tblMember " +
                                                    " WHERE Username = ? " +
                                                    " AND Password = ? ";
                    pre = connect.prepareStatement(sql);
                    pre.setString(1, GlobalVar.userName);
                    pre.setString(2, GlobalVar.passWord);

                    ResultSet rec = pre.executeQuery();
                    if(rec.next()) {
                            GlobalVar.name = rec.getString("name");
                            GlobalVar.memberType = rec.getString("MemberType");
                            status=true;
                            GlobalVar.status= status;
                    }else {
                            JOptionPane.showMessageDialog(null, Lang.option_dialog_massage_fail, Lang.option_dialog_title, JOptionPane.WARNING_MESSAGE);
                    }

            }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    e.printStackTrace();
            }
            //Close connection
            try {
                    if(pre != null) {
                            pre.close();
                            connect.close();
                    }

            }catch (SQLException e) {
                    System.out.println(e.getMessage());
                    e.printStackTrace();
            }
            return status;
    }
    
    public static void OpenDialog() {
            LoginDialog login = new LoginDialog();
            login.setModal(true);
            login.setVisible(true);
            //get value
            GlobalVar.userName = login.username;
            GlobalVar.passWord = login.password;

            //Check Login
            if(!getLogin()) {
                    OpenDialog();		//Login agin
            }else {
                    JOptionPane.showMessageDialog(null, "Hi  " + GlobalVar.name);
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnBookManager = new javax.swing.JButton();
        btnMemberManager = new javax.swing.JButton();
        btnBorrows = new javax.swing.JButton();
        btnBorrows1 = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnHoliday = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        itemClose = new javax.swing.JMenuItem();
        mnuBook = new javax.swing.JMenu();
        itemBorrow = new javax.swing.JMenuItem();
        itemReturn = new javax.swing.JMenuItem();
        itemBookData = new javax.swing.JMenuItem();
        itemBookType = new javax.swing.JMenuItem();
        mnuMember = new javax.swing.JMenu();
        itemMember = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        mnuSetting = new javax.swing.JMenu();
        itwmDatabase = new javax.swing.JMenuItem();
        itemNetworkSetup = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jToolBar1.setRollover(true);

        btnBookManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/book224.png"))); // NOI18N
        btnBookManager.setText("ข้อมูลหนังสือ");
        btnBookManager.setFocusable(false);
        btnBookManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBookManager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBookManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookManagerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBookManager);

        btnMemberManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/student24.png"))); // NOI18N
        btnMemberManager.setText("สมาชิก");
        btnMemberManager.setFocusable(false);
        btnMemberManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMemberManager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMemberManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberManagerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMemberManager);

        btnBorrows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/library.png"))); // NOI18N
        btnBorrows.setText("ยืมหนังสือ");
        btnBorrows.setFocusable(false);
        btnBorrows.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrows.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBorrows);

        btnBorrows1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/booksreturn24.png"))); // NOI18N
        btnBorrows1.setText("คืนหนังสือ");
        btnBorrows1.setFocusable(false);
        btnBorrows1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrows1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBorrows1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrows1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBorrows1);

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/board24.png"))); // NOI18N
        btnReport.setText("รายงาน");
        btnReport.setFocusable(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnReport);

        btnHoliday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/calendar24.png"))); // NOI18N
        btnHoliday.setText("วันหยุด");
        btnHoliday.setFocusable(false);
        btnHoliday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoliday.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHoliday);

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/computer24.png"))); // NOI18N
        btnConnect.setText("ฐานข้อมูล");
        btnConnect.setFocusable(false);
        btnConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConnect);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/key.png"))); // NOI18N
        btnClose.setText("ออกจากโปรแกรม");
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClose);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 562, 51);
        getContentPane().add(desktop);
        desktop.setBounds(0, 60, 1270, 700);

        mnuFile.setText("ไฟล์");

        itemClose.setText("ปิดโปรแกรม");
        itemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCloseActionPerformed(evt);
            }
        });
        mnuFile.add(itemClose);

        jMenuBar1.add(mnuFile);

        mnuBook.setText("หนังสือ");

        itemBorrow.setText("ยืมหนังสือ");
        itemBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBorrowActionPerformed(evt);
            }
        });
        mnuBook.add(itemBorrow);

        itemReturn.setText("คืนหนังสือ");
        itemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReturnActionPerformed(evt);
            }
        });
        mnuBook.add(itemReturn);

        itemBookData.setText("จัดการข้อมูลหนังสือ");
        itemBookData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBookDataActionPerformed(evt);
            }
        });
        mnuBook.add(itemBookData);

        itemBookType.setText("ประเภทหนังสือ");
        itemBookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBookTypeActionPerformed(evt);
            }
        });
        mnuBook.add(itemBookType);

        jMenuBar1.add(mnuBook);

        mnuMember.setText("สมาชิก");

        itemMember.setText("จัดการผู้ใช้");
        itemMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMemberActionPerformed(evt);
            }
        });
        mnuMember.add(itemMember);

        jMenuBar1.add(mnuMember);

        mnuReport.setText("รายงาน");
        jMenuBar1.add(mnuReport);

        mnuSetting.setText("ตั้งค่า");

        itwmDatabase.setText("วันหยุด");
        mnuSetting.add(itwmDatabase);

        itemNetworkSetup.setText("ฐานข้อมูล");
        itemNetworkSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNetworkSetupActionPerformed(evt);
            }
        });
        mnuSetting.add(itemNetworkSetup);

        jMenuBar1.add(mnuSetting);

        mnuAbout.setText("เกี่ยวกับ");
        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookManagerActionPerformed
        BookManager manage= new BookManager();
        manage.setVisible(true);
        desktop.add(manage);
        try{
                manage.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_btnBookManagerActionPerformed

    private void itemMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMemberActionPerformed
        // TODO add your handling code here:
        MemberManager manage= new MemberManager();
        manage.setVisible(true);
        desktop.add(manage);
        try{
                manage.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_itemMemberActionPerformed

    private void itemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCloseActionPerformed
        int c = 0;
        c = JOptionPane.showConfirmDialog(null, Lang.option_dialog_massage_close);
        if(c==0) {
                //Close InternalForm
                 System.exit(0);
        }
    }//GEN-LAST:event_itemCloseActionPerformed

    private void itemBookDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBookDataActionPerformed
         BookManager manage= new BookManager();
        manage.setVisible(true);
        desktop.add(manage);
        try{
                manage.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_itemBookDataActionPerformed

    private void btnMemberManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberManagerActionPerformed
        MemberManager manage= new MemberManager();
        manage.setVisible(true);
        desktop.add(manage);
        try{
                manage.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_btnMemberManagerActionPerformed

    private void btnBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowsActionPerformed
        BooksBorrow borrows = new BooksBorrow();
        borrows.setVisible(true);
        desktop.add(borrows);
        try{
                borrows.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnBorrowsActionPerformed

    private void btnBorrows1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrows1ActionPerformed
         BooksReturn bookreturn = new BooksReturn();
        bookreturn.setVisible(true);
        desktop.add(bookreturn);
        try{
                bookreturn.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_btnBorrows1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       int c = 0;
        c = JOptionPane.showConfirmDialog(null, Lang.option_dialog_massage_close);
        if(c==0) {
                //Close InternalForm
                 System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void itemBookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBookTypeActionPerformed
         BookTypeManage booktype = new BookTypeManage();
        booktype.setVisible(true);
        desktop.add(booktype);
        try{
                booktype.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_itemBookTypeActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        NetworkSetup networksetup = new NetworkSetup();
        networksetup.setVisible(true);
        desktop.add(networksetup);
        try{
                networksetup.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void itemNetworkSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNetworkSetupActionPerformed
        NetworkSetup networksetup = new NetworkSetup();
        networksetup.setVisible(true);
        desktop.add(networksetup);
        try{
                networksetup.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_itemNetworkSetupActionPerformed

    private void itemBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBorrowActionPerformed
        BooksBorrow borrows = new BooksBorrow();
        borrows.setVisible(true);
        desktop.add(borrows);
        try{
                borrows.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_itemBorrowActionPerformed

    private void itemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnActionPerformed
        BooksReturn bookreturn = new BooksReturn();
        bookreturn.setVisible(true);
        desktop.add(bookreturn);
        try{
                bookreturn.setSelected(true);
        }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_itemReturnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         if(GlobalVar.status.equals(false)) {
               //OpenDialog();
        }
        //Render Menu Show
        if(GlobalVar.memberType.equals("Admin")) {
                itemBorrow.setVisible(true);
                itemReturn.setVisible(true);
                itemBookData.setVisible(true); 	//Book             
        }else {
                 //JOptionPane.showMessageDialog(this, Lang.option_dialog_massage_fail, "เฉพาะเจ้าหน้าที่เท่านั้น", JOptionPane.WARNING_MESSAGE);
                //OpenDialog();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookManager;
    private javax.swing.JButton btnBorrows;
    private javax.swing.JButton btnBorrows1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnHoliday;
    private javax.swing.JButton btnMemberManager;
    private javax.swing.JButton btnReport;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itemBookData;
    private javax.swing.JMenuItem itemBookType;
    private javax.swing.JMenuItem itemBorrow;
    private javax.swing.JMenuItem itemClose;
    private javax.swing.JMenuItem itemMember;
    private javax.swing.JMenuItem itemNetworkSetup;
    private javax.swing.JMenuItem itemReturn;
    private javax.swing.JMenuItem itwmDatabase;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuBook;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuMember;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuSetting;
    // End of variables declaration//GEN-END:variables
}
