/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Book;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manage.DbConnect;
import manage.GlobalVar;
import manage.Lang;

/**
 *
 * @author khanchaiwongsit
 */
public class BookTypeManage extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookTypeManage
     */
    private String strID;
    private String strCode;
    private String strBookName;
    
    public BookTypeManage() {
        initComponents();
        
         setTitle(Lang.menu_member_manage);
        //set size
        int width = 660;
        int height = 420;
        setBounds(GlobalVar.screenCenterX-(width/2),20,width,height);
        
        showBookTypeInTable();
       
    }
    //Class to ArrayList object
    public ArrayList<BookType> getBookTypeList(){
        ArrayList<BookType> booktypeList = new ArrayList<BookType>();
        Connection con = DbConnect.getConnection();
        
         // Sql Command              
        String sql = "SELECT * FROM tblBookType ";
        //Variable Statement and Resultset
        Statement st;
        ResultSet rs;
        //
        try{
            st = con.createStatement();     //Create Statement
            rs = st.executeQuery(sql);
            BookType booktype;
            while(rs.next()){
                booktype = new BookType(rs.getInt("ID"),rs.getString("Code"),rs.getString("BookName"));
                booktypeList.add(booktype);
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        return booktypeList;
    }
    
    //Show data to Table
    public void showBookTypeInTable(){
        ArrayList<BookType> list = getBookTypeList();
        DefaultTableModel model = (DefaultTableModel)tblBookType.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getCode();
            row[2] = list.get(i).getBookName();            
            model.addRow(row);
        }
        txtID.disable();
    }
    
    //execute Query 
    public void executeSQLQuery(String query, String message){
        Connection con = DbConnect.getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1){
                 //refreash Table
                DefaultTableModel model = (DefaultTableModel)tblBookType.getModel();
                 model.setRowCount(0);
                 showBookTypeInTable();
                 //clearTextField();
                 //Show message dialog
                JOptionPane.showMessageDialog(this, "Data " + message + " Sucessfuly");
            }else{
                JOptionPane.showMessageDialog(this, "Data not " + message);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
   
    //Clear TextField
    public void clearTextField(){
        //Reset TextField
        txtID.setText("");
        txtCode.setText("");
        txtBookName.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookType = new javax.swing.JTable();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/bookreturn32.png"))); // NOI18N
        jLabel5.setText("Book Type");

        txtID.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel2.setText("ID :");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/plus24.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/x-button32.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/remove32.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/refresh32.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel3.setText("Code :");

        txtCode.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel4.setText("Book Name :");

        txtBookName.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N

        tblBookType.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        tblBookType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "BookName"
            }
        ));
        tblBookType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBookType);
        if (tblBookType.getColumnModel().getColumnCount() > 0) {
            tblBookType.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblBookType.getColumnModel().getColumn(1).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int c = 0;
        c = JOptionPane.showConfirmDialog(this, "You sure delete this row in Table ?.");
        if(c==0) {
                // Delete Record
                String sql = "DELETE FROM tblBookType WHERE ID='" + txtID.getText() + "'";
                //
                executeSQLQuery(sql, "Deleted");
                clearTextField();
        }else {

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //input value to variable
            strID = txtID.getText();
            strCode = txtCode.getText();
            strBookName = txtBookName.getText();

         //Check input value
            if(strCode.equals("")) {			//Check User ID
                    JOptionPane.showMessageDialog(this, Lang.warn_textfild_null + "Code ", Lang.warn_title, JOptionPane.WARNING_MESSAGE);
                    txtCode.requestFocusInWindow();
                    //return false;
            }else if(strBookName.equals("")) {			//Check Name
                    JOptionPane.showMessageDialog(this, Lang.warn_textfild_null + "Book Name", Lang.warn_title, JOptionPane.WARNING_MESSAGE);
                    txtBookName.requestFocusInWindow();
                    //return false;
            }else {
                //Insert Record
                String sql = "INSERT INTO tblBookType (ID,Code,BookName) VALUES (null,'"+
                strCode + "','" +
                strBookName + "')";
                
                //System.out.print(sql);
                //Execute Query database
                executeSQLQuery(sql, "Inserted");
                //Clear
                clearTextField();
            }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //input value to variable
            strID = txtID.getText();
            strCode = txtCode.getText();
            strBookName = txtBookName.getText();

         //Check input value
            if(strCode.equals("")) {			//Check User ID
                    JOptionPane.showMessageDialog(this, Lang.warn_textfild_null + "Code ", Lang.warn_title, JOptionPane.WARNING_MESSAGE);
                    txtCode.requestFocusInWindow();
                    //return false;
            }else if(strBookName.equals("")) {			//Check Name
                    JOptionPane.showMessageDialog(this, Lang.warn_textfild_null + "Book Name", Lang.warn_title, JOptionPane.WARNING_MESSAGE);
                    txtBookName.requestFocusInWindow();
                    //return false;
            }else {
                //Update
                String sql = "UPDATE tblBookType SET " +
                                " Code ='" + strCode +"',"+
                                " BookName ='" + strBookName +"'"+
                               " WHERE  ID = '" + strID + "'";
                
                System.out.print(sql);
                //Execute Query database
                executeSQLQuery(sql, "Inserted");
                //Clear
                clearTextField();
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBookTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookTypeMouseClicked
        int row = tblBookType.getSelectedRow();		//get select row
        
        //get value to TextField
        String strID = tblBookType.getValueAt(row, 0).toString();
        txtID.setText(strID);
        //
        String strCode = tblBookType.getValueAt(row, 1).toString();
        txtCode.setText(strCode);
        //
        String strBookName = tblBookType.getValueAt(row, 2).toString();
        txtBookName.setText(strBookName);
    }//GEN-LAST:event_tblBookTypeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBookType;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
